---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Install 'procps' before installation of openjdk
      apt:
        name:
          - procps
        update_cache: yes

  roles:
    - role: pmoscode.airsonic
#    - role: airsonic
